[databases]
# Add one line per database.
# The create-pg-db.sh script appends here automatically.
postgres = host=postgres port=5432 dbname=postgres

[pgbouncer]
listen_addr       = 0.0.0.0
listen_port       = 5432
auth_type         = md5
auth_file         = /etc/pgbouncer/userlist.txt
pool_mode         = session
max_client_conn   = 200
default_pool_size = 25
reserve_pool_size = 5
server_reset_query = DISCARD ALL
log_connections   = 0
log_disconnections = 0
ignore_startup_parameters = extra_float_digits
